config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :movies, :series, :documentry_films
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentry_film.rb
class DocumentryFilm < ApplicationRecord
    validates :name, presence: true, length: {minimum: 6, maximun: 100} 
    validates :synopsis, presence: true, length: {minimum: 10, maximun: 500} 
    validates :director, presence: true, length: {minimum: 6, maximun: 100} 
end

app/models/movie.rb
class Movie < ApplicationRecord
    validates :name, presence: true, length: {minimum: 6, maximun: 100} 
    validates :synopsis, presence: true, length: {minimum: 10, maximun: 500} 
    validates :director, presence: true, length: {minimum: 6, maximun: 100} 
end

app/models/serie.rb
class Serie < ApplicationRecord
    validates :name, presence: true, length: {minimum: 6, maximun: 100} 
    validates :synopsis, presence: true, length: {minimum: 10, maximun: 500} 
    validates :director, presence: true, length: {minimum: 6, maximun: 100} 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/documentry_films_controller.rb
class DocumentryFilmsController < ApplicationController
    before_action :set_documentary, only: [:show, :edit, :update, :destroy]
    def show
    end

    def index
        @documentryfilms = DocumentryFilm.all
    end

    def new
        @documentryfilm = DocumentryFilm.new
    end

    def edit
    end

    def create
        @documentryfilm = DocumentryFilm.new(documentary_params)
        if @documentryfilm.save
            flash[:notice] = "Documentary was created successfully."
            redirect_to @documentryfilm
        else
            render :new, status: 422
        end
    end

    def update
        if @documentryfilm.update(documentary_params)
            flash[:notice] = "Documentary was update successfully"
            redirect_to @documentryfilm
        else
            render 'edit'
        end
    end

    def destroy
        @documentryfilm.destroy
        redirect_to documentry_films_path
    end

    # refactorizamos el codigo con el metodo set_documentary y documentaryparams
    private
    def set_documentary
        @documentryfilm = DocumentryFilm.find(params[:id])
    end

    def documentary_params
        params.require(:documentryfilm).permit(:name, :synopsis, :director)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    before_action :set_movie, only: [:show, :edit, :update, :destroy]
    def show
    end

    def index
        @movies = Movie.all
    end

    def new
        @movie = Movie.new
    end

    def edit
    end

    def create
        @movie = Movie.new(movie_params)
        if @movie.save
            flash[:notice] = "movie was created successfully."
            redirect_to @movie
        else
            render :new, status: 422
        end
    end

    def update
        if @movie.update(movie_params)
            flash[:notice] = "Movie was update successfully"
            redirect_to @movie
        else
            render 'edit'
        end
    end

    def destroy
        @movie.destroy
        redirect_to movies_path
    end
    # refactorizamos el codigo con el metodo set_movie
    private
    def set_movie
        @movie = Movie.find(params[:id])
    end

    def movie_params
        params.require(:movie).permit(:name, :synopsis, :director)
    end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
    before_action :set_serie, only: [:show, :edit, :update, :destroy]
    
    def show
    end

    def index
        @series = Serie.all
    end

    def new
        @serie = Serie.new
    end

    def edit
    end

    def create
        @serie = Serie.new(serie_params)
        if @serie.save
            flash[:notice] = "Serie was created successfully."
            redirect_to @serie
        else
            render :new, status: 422
        end
    end

    def update
        if @serie.update(serie_params)
            flash[:notice] = "Movie was update successfully"
            redirect_to @serie
        else
            render 'edit'
        end
    end

    def destroy
        @serie.destroy
        redirect_to series_index_path
    end
    # refactorizamos el codigo con el metodo set_movie
    private
    def set_serie
        @serie = Serie.find(params[:id])
    end

    def serie_params
        params.require(:serie).permit(:name, :synopsis, :director)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/documentry_films/_form.html.erb
<% if @documentryfilm.errors.any? %>
    <h2>The following errors prevented the movie from being saved</h2>
    <ul>
        <% @documentryfilm.errors.full_messages.each do |msg|%>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_with(model: @documentryfilm, local: true) do |f|%>
    <p>
        <%= f.label :name %><br/>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.label :synopsis %><br/>
        <%= f.text_area :synopsis %>
    </p>

    <p>
        <%= f.label :director %><br/>
        <%= f.text_field :director %>
    </p>

    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/documentry_films/edit.html.erb
<h1>Edit Documentary</h1>

<%= render 'form'%>
<p>
    <%= link_to 'Create new documentary', documentry_films_path%>
</p>
<p>
    <%= link_to 'Return to documentary films listing', documentry_films_path%>
</p>

app/views/documentry_films/index.html.erb
<h1>Documentary films listing page</h1>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Synopsis</th>
            <th>Director</th>
        </tr>
    </thead>
    <tbody>
        <% @documentryfilms.each do |documentry|%>
        <tr>
            <td><%= documentry.name%></td>
            <td><%= documentry.synopsis%></td>
            <td><%= documentry.director%></td>
            <td><%= link_to 'Show', documentry_film_path(documentry)%></td>
            <td><%= button_to 'Delete', documentry_film_path(documentry), method: :delete, data: {confirm: "Are you sure"}  %></td>
            <td><%= link_to 'Edit', edit_documentry_film_path(documentry), method: :update %></td>
        </tr>
        <% end %>
    </tbody>
</table>
<p>
    <%= link_to 'Create new documentary films', new_documentry_film_path%>
    
</p>

app/views/documentry_films/new.html.erb
<h1>Create a new Document</h1>

<%= render 'form'%>

<p>
    <%= link_to 'Return to documentary films listing', documentry_films_path%>
</p>

app/views/documentry_films/show.html.erb
<h1>Showing documentary details</h1>

<p><strong>Name: </strong><%= @documentryfilm.name%></p>
<p><strong>Synopsis: </strong><%= @documentryfilm.synopsis%></p>
<p><strong>Director: </strong><%= @documentryfilm.director%></p>
<p>
    <%= link_to 'Return to documentary films listing', documentry_films_path%>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheFilms</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name, msg| %> 
      <%= msg %> 
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<% if @movie.errors.any? %>
    <h2>The following errors prevented the movie from being saved</h2>
    <ul>
        <% @movie.errors.full_messages.each do |msg|%>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_with(model: @movie, local: true) do |f|%>
    <p>
        <%= f.label :name %><br/>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.label :synopsis %><br/>
        <%= f.text_area :synopsis %>
    </p>

    <p>
        <%= f.label :director %><br/>
        <%= f.text_field :director %>
    </p>

    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/movies/edit.html.erb
<h1>Edit Movie</h1>

<%= render 'form'%>

<%= link_to 'Return to movies listing', movies_path%>

app/views/movies/index.html.erb
<h1>Movies listing page</h1>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Synopsis</th>
            <th>Director</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @movies.each do |movie|%>
        <tr>
            <td><%= movie.name%></td>
            <td><%= movie.synopsis%></td>
            <td><%= movie.director%></td>
            <td><%= link_to 'Show', movie_path(movie)%></td>
            <td><%= button_to 'Delete', movie_path(movie), method: :delete, data: {confirm: "Are you sure"}  %></td>
            <td><%= link_to 'Edit', edit_movie_path(movie), method: :update %></td>
        </tr>
        <% end %>
    </tbody>
</table>
<p>
    <%= link_to 'Create new movie', new_movie_path%>
</p>

app/views/movies/new.html.erb
<h1>Create a new Movie</h1>

<%= render 'form'%>

<%= link_to 'Return to movies listing', movies_path%>

app/views/movies/show.html.erb
<h1>Showing movies details</h1>

<p><strong>Name: </strong><%= @movie.name%></p>
<p><strong>Synopsis: </strong><%= @movie.synopsis%></p>
<p><strong>Director: </strong><%= @movie.director%></p>

<%= link_to 'Edit', edit_movie_path(@movie)%>
<%= button_to 'Delete', movie_path(@movie), method: :delete, data: {confirm: "Are you sure"} %>
<%= link_to 'Return to movies listing', movies_path%>
<%= link_to 'Create new article', new_movie_path%>

app/views/series/_form.html.erb
<% if @serie.errors.any? %>
    <h2>The following errors prevented the movie from being saved</h2>
    <ul>
        <% @serie.errors.full_messages.each do |msg|%>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_with(model: @serie, local: true) do |f|%>
    <p>
        <%= f.label :name %><br/>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.label :synopsis %><br/>
        <%= f.text_area :synopsis %>
    </p>

    <p>
        <%= f.label :director %><br/>
        <%= f.text_field :director %>
    </p>

    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/series/edit.html.erb
<h1>Edit Serie</h1>

<%= render 'form'%>
<%= link_to 'Return to series listing', series_index_path%>

app/views/series/index.html.erb
<h1>Series listing page</h1>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Synopsis</th>
            <th>Director</th>
        </tr>
    </thead>
    <tbody>
        <% @series.each do |serie|%>
        <tr>
            <td><%= serie.name%></td>
            <td><%= serie.synopsis%></td>
            <td><%= serie.director%></td>
             <td><%= link_to 'Show', series_path(serie)%></td>
            <td><%= button_to 'Delete', series_path(serie), method: :delete, data: {confirm: "Are you sure"}  %></td>
            <td><%= link_to 'Edit', edit_series_path(serie), method: :update %></td>
        </tr>
        <% end %>
    </tbody>
</table>
<p>
    <%= link_to 'Create new serie', new_series_path%>
</p>

app/views/series/new.html.erb
<h1>Create a new Serie</h1>

<% if @serie.errors.any? %>
    <h2>The following errors prevented the movie from being saved</h2>
    <ul>
        <% @serie.errors.full_messages.each do |msg|%>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_with scope: :serie, url: series_index_path, local: true do |f|%>
    <p>
        <%= f.label :name %><br/>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.label :synopsis %><br/>
        <%= f.text_area :synopsis %>
    </p>

    <p>
        <%= f.label :director %><br/>
        <%= f.text_field :director %>
    </p>

    <p>
        <%= f.submit %>
    </p>
<% end %>
<%= link_to 'Return to series listing', series_index_path%>

app/views/series/show.html.erb
<h1>Showing series details</h1>

<p><strong>Name: </strong><%= @serie.name%></p>
<p><strong>Synopsis: </strong><%= @serie.synopsis%></p>
<p><strong>Director: </strong><%= @serie.director%></p>

<%= link_to 'Edit', edit_series_path(@serie)%>
<%= button_to 'Delete', series_path(@serie), method: :delete, data: {confirm: "Are you sure"} %>
<%= link_to 'Return to series listing', series_index_path%>
<%= link_to 'Create new serie', new_series_path%>